# Generated by Django 3.1.7 on 2021-04-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jb_main', '0002_auto_20210402_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='joke',
            name='author',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='joke',
            name='source',
            field=models.CharField(blank=True, default='unknown', max_length=50),
        ),
    ]
