# Generated by Django 3.1.7 on 2021-04-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jb_main', '0003_auto_20210402_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='user_id',
            new_name='user',
        ),
    ]
