# Generated by Django 3.1.7 on 2021-04-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jb_main', '0006_auto_20210403_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='user',
        ),
    ]
